name: Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository

      - name: Setup PHP with tools
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: parallel-lint

  dependencies:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Run linter (parallel-lint)
        run: composer run-script test:lint

  unit:
    runs-on: ubuntu-latest

    steps:
      - name: Run Unit Tests (Pest)
        run: composer run-script test:unit

  content:
    runs-on: ubuntu-latest

    steps:
      - name: Run functional tests (API, pages)
        run: |
          php tests/Functional/pages.php
          php tests/Functional/api.php

  static:
    runs-on: ubuntu-latest

    steps:
      - name: Run static analysis (PHPStan)
        run: composer run-script test:static
